name: Pest Coverage and Type-Coverage > 90%

on: [push, pull_request]

jobs:

  pest-type-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, dom
          tools: composer

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-vendor-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run Pest Tests with Type Coverage
        run: vendor/bin/pest --type-coverage --min=90

  pest-code-coverage:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: mlbrgn_form_test
          MARIADB_USER: root
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, dom, xdebug
          tools: composer

      - name: Cache Composer Dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-vendor-

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      - name: Install Node dependencies
        run: npm install

      - name: Generated JS and CSS cache
        id: js-and-css-cache
        uses: actions/cache@v4
        with:
          path: public/build/**
          key: ${{ runner.os }}-js-and-css-${{ hashFiles('**/package-lock.json', '**/resources/{.js,scss}') }}

      - name: Generate front-end files
        if: steps.js-and-css-cache.outputs.cache-hit != 'true'
        run: npm run build

      - name: Prepare Laravel environment
        run: |
          cp .env.github .env
          php artisan key:generate
          php artisan migrate
          php artisan passport:keys

      - name: Run Code Coverage
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/pest --coverage --min=80

  combine-results:
    runs-on: ubuntu-latest
    needs: [pest-type-coverage, pest-code-coverage]

    steps:
      - name: Output Summary
        run: echo "Type Coverage and Code Coverage completed successfully."
